language: java

scala:
   - 2.12.1

sudo: required
addons:
  apt:
    packages:
      - oracle-java8-installer

jdk:
  - oraclejdk8

install: true
      
script:
   - sbt ++$TRAVIS_SCALA_VERSION clean compile test
